# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkers.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button11 = QtWidgets.QPushButton(self.centralwidget)
        self.button11.setGeometry(QtCore.QRect(40, 30, 51, 51))
        self.button11.setText("")
        self.button11.setObjectName("button11")
        self.button12 = QtWidgets.QPushButton(self.centralwidget)
        self.button12.setGeometry(QtCore.QRect(90, 30, 51, 51))
        self.button12.setText("")
        self.button12.setObjectName("button12")
        self.button13 = QtWidgets.QPushButton(self.centralwidget)
        self.button13.setGeometry(QtCore.QRect(140, 30, 51, 51))
        self.button13.setText("")
        self.button13.setObjectName("button13")
        self.button14 = QtWidgets.QPushButton(self.centralwidget)
        self.button14.setGeometry(QtCore.QRect(190, 30, 51, 51))
        self.button14.setText("")
        self.button14.setObjectName("button14")
        self.button15 = QtWidgets.QPushButton(self.centralwidget)
        self.button15.setGeometry(QtCore.QRect(240, 30, 51, 51))
        self.button15.setText("")
        self.button15.setObjectName("button15")
        self.button16 = QtWidgets.QPushButton(self.centralwidget)
        self.button16.setGeometry(QtCore.QRect(290, 30, 51, 51))
        self.button16.setText("")
        self.button16.setObjectName("button16")
        self.button17 = QtWidgets.QPushButton(self.centralwidget)
        self.button17.setGeometry(QtCore.QRect(340, 30, 51, 51))
        self.button17.setText("")
        self.button17.setObjectName("button17")
        self.button18 = QtWidgets.QPushButton(self.centralwidget)
        self.button18.setGeometry(QtCore.QRect(390, 30, 51, 51))
        self.button18.setText("")
        self.button18.setObjectName("button18")
        self.buttonPasar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPasar.setGeometry(QtCore.QRect(200, 460, 80, 23))
        self.buttonPasar.setObjectName("buttonPasar")
        self.button22 = QtWidgets.QPushButton(self.centralwidget)
        self.button22.setGeometry(QtCore.QRect(90, 80, 51, 51))
        self.button22.setText("")
        self.button22.setObjectName("button22")
        self.button28 = QtWidgets.QPushButton(self.centralwidget)
        self.button28.setGeometry(QtCore.QRect(390, 80, 51, 51))
        self.button28.setText("")
        self.button28.setObjectName("button28")
        self.button23 = QtWidgets.QPushButton(self.centralwidget)
        self.button23.setGeometry(QtCore.QRect(140, 80, 51, 51))
        self.button23.setText("")
        self.button23.setObjectName("button23")
        self.button26 = QtWidgets.QPushButton(self.centralwidget)
        self.button26.setGeometry(QtCore.QRect(290, 80, 51, 51))
        self.button26.setText("")
        self.button26.setObjectName("button26")
        self.button21 = QtWidgets.QPushButton(self.centralwidget)
        self.button21.setGeometry(QtCore.QRect(40, 80, 51, 51))
        self.button21.setText("")
        self.button21.setObjectName("button21")
        self.button25 = QtWidgets.QPushButton(self.centralwidget)
        self.button25.setGeometry(QtCore.QRect(240, 80, 51, 51))
        self.button25.setText("")
        self.button25.setObjectName("button25")
        self.button24 = QtWidgets.QPushButton(self.centralwidget)
        self.button24.setGeometry(QtCore.QRect(190, 80, 51, 51))
        self.button24.setText("")
        self.button24.setObjectName("button24")
        self.button27 = QtWidgets.QPushButton(self.centralwidget)
        self.button27.setGeometry(QtCore.QRect(340, 80, 51, 51))
        self.button27.setText("")
        self.button27.setObjectName("button27")
        self.button32 = QtWidgets.QPushButton(self.centralwidget)
        self.button32.setGeometry(QtCore.QRect(90, 130, 51, 51))
        self.button32.setText("")
        self.button32.setObjectName("button32")
        self.button38 = QtWidgets.QPushButton(self.centralwidget)
        self.button38.setGeometry(QtCore.QRect(390, 130, 51, 51))
        self.button38.setText("")
        self.button38.setObjectName("button38")
        self.button33 = QtWidgets.QPushButton(self.centralwidget)
        self.button33.setGeometry(QtCore.QRect(140, 130, 51, 51))
        self.button33.setText("")
        self.button33.setObjectName("button33")
        self.button36 = QtWidgets.QPushButton(self.centralwidget)
        self.button36.setGeometry(QtCore.QRect(290, 130, 51, 51))
        self.button36.setText("")
        self.button36.setObjectName("button36")
        self.button31 = QtWidgets.QPushButton(self.centralwidget)
        self.button31.setGeometry(QtCore.QRect(40, 130, 51, 51))
        self.button31.setText("")
        self.button31.setObjectName("button31")
        self.button35 = QtWidgets.QPushButton(self.centralwidget)
        self.button35.setGeometry(QtCore.QRect(240, 130, 51, 51))
        self.button35.setText("")
        self.button35.setObjectName("button35")
        self.button34 = QtWidgets.QPushButton(self.centralwidget)
        self.button34.setGeometry(QtCore.QRect(190, 130, 51, 51))
        self.button34.setText("")
        self.button34.setObjectName("button34")
        self.button37 = QtWidgets.QPushButton(self.centralwidget)
        self.button37.setGeometry(QtCore.QRect(340, 130, 51, 51))
        self.button37.setText("")
        self.button37.setObjectName("button37")
        self.button42 = QtWidgets.QPushButton(self.centralwidget)
        self.button42.setGeometry(QtCore.QRect(90, 180, 51, 51))
        self.button42.setText("")
        self.button42.setObjectName("button42")
        self.button48 = QtWidgets.QPushButton(self.centralwidget)
        self.button48.setGeometry(QtCore.QRect(390, 180, 51, 51))
        self.button48.setText("")
        self.button48.setObjectName("button48")
        self.button43 = QtWidgets.QPushButton(self.centralwidget)
        self.button43.setGeometry(QtCore.QRect(140, 180, 51, 51))
        self.button43.setText("")
        self.button43.setObjectName("button43")
        self.button46 = QtWidgets.QPushButton(self.centralwidget)
        self.button46.setGeometry(QtCore.QRect(290, 180, 51, 51))
        self.button46.setText("")
        self.button46.setObjectName("button46")
        self.button41 = QtWidgets.QPushButton(self.centralwidget)
        self.button41.setGeometry(QtCore.QRect(40, 180, 51, 51))
        self.button41.setText("")
        self.button41.setObjectName("button41")
        self.button45 = QtWidgets.QPushButton(self.centralwidget)
        self.button45.setGeometry(QtCore.QRect(240, 180, 51, 51))
        self.button45.setText("")
        self.button45.setObjectName("button45")
        self.button44 = QtWidgets.QPushButton(self.centralwidget)
        self.button44.setGeometry(QtCore.QRect(190, 180, 51, 51))
        self.button44.setText("")
        self.button44.setObjectName("button44")
        self.button47 = QtWidgets.QPushButton(self.centralwidget)
        self.button47.setGeometry(QtCore.QRect(340, 180, 51, 51))
        self.button47.setText("")
        self.button47.setObjectName("button47")
        self.button52 = QtWidgets.QPushButton(self.centralwidget)
        self.button52.setGeometry(QtCore.QRect(90, 230, 51, 51))
        self.button52.setText("")
        self.button52.setObjectName("button52")
        self.button58 = QtWidgets.QPushButton(self.centralwidget)
        self.button58.setGeometry(QtCore.QRect(390, 230, 51, 51))
        self.button58.setText("")
        self.button58.setObjectName("button58")
        self.button53 = QtWidgets.QPushButton(self.centralwidget)
        self.button53.setGeometry(QtCore.QRect(140, 230, 51, 51))
        self.button53.setText("")
        self.button53.setObjectName("button53")
        self.button56 = QtWidgets.QPushButton(self.centralwidget)
        self.button56.setGeometry(QtCore.QRect(290, 230, 51, 51))
        self.button56.setText("")
        self.button56.setObjectName("button56")
        self.button51 = QtWidgets.QPushButton(self.centralwidget)
        self.button51.setGeometry(QtCore.QRect(40, 230, 51, 51))
        self.button51.setText("")
        self.button51.setObjectName("button51")
        self.button55 = QtWidgets.QPushButton(self.centralwidget)
        self.button55.setGeometry(QtCore.QRect(240, 230, 51, 51))
        self.button55.setText("")
        self.button55.setObjectName("button55")
        self.button54 = QtWidgets.QPushButton(self.centralwidget)
        self.button54.setGeometry(QtCore.QRect(190, 230, 51, 51))
        self.button54.setText("")
        self.button54.setObjectName("button54")
        self.button57 = QtWidgets.QPushButton(self.centralwidget)
        self.button57.setGeometry(QtCore.QRect(340, 230, 51, 51))
        self.button57.setText("")
        self.button57.setObjectName("button57")
        self.button62 = QtWidgets.QPushButton(self.centralwidget)
        self.button62.setGeometry(QtCore.QRect(90, 280, 51, 51))
        self.button62.setText("")
        self.button62.setObjectName("button62")
        self.button68 = QtWidgets.QPushButton(self.centralwidget)
        self.button68.setGeometry(QtCore.QRect(390, 280, 51, 51))
        self.button68.setText("")
        self.button68.setObjectName("button68")
        self.button63 = QtWidgets.QPushButton(self.centralwidget)
        self.button63.setGeometry(QtCore.QRect(140, 280, 51, 51))
        self.button63.setText("")
        self.button63.setObjectName("button63")
        self.button66 = QtWidgets.QPushButton(self.centralwidget)
        self.button66.setGeometry(QtCore.QRect(290, 280, 51, 51))
        self.button66.setText("")
        self.button66.setObjectName("button66")
        self.button61 = QtWidgets.QPushButton(self.centralwidget)
        self.button61.setGeometry(QtCore.QRect(40, 280, 51, 51))
        self.button61.setText("")
        self.button61.setObjectName("button61")
        self.button65 = QtWidgets.QPushButton(self.centralwidget)
        self.button65.setGeometry(QtCore.QRect(240, 280, 51, 51))
        self.button65.setText("")
        self.button65.setObjectName("button65")
        self.button64 = QtWidgets.QPushButton(self.centralwidget)
        self.button64.setGeometry(QtCore.QRect(190, 280, 51, 51))
        self.button64.setText("")
        self.button64.setObjectName("button64")
        self.button67 = QtWidgets.QPushButton(self.centralwidget)
        self.button67.setGeometry(QtCore.QRect(340, 280, 51, 51))
        self.button67.setText("")
        self.button67.setObjectName("button67")
        self.button72 = QtWidgets.QPushButton(self.centralwidget)
        self.button72.setGeometry(QtCore.QRect(90, 330, 51, 51))
        self.button72.setText("")
        self.button72.setObjectName("button72")
        self.button78 = QtWidgets.QPushButton(self.centralwidget)
        self.button78.setGeometry(QtCore.QRect(390, 330, 51, 51))
        self.button78.setText("")
        self.button78.setObjectName("button78")
        self.button73 = QtWidgets.QPushButton(self.centralwidget)
        self.button73.setGeometry(QtCore.QRect(140, 330, 51, 51))
        self.button73.setText("")
        self.button73.setObjectName("button73")
        self.button76 = QtWidgets.QPushButton(self.centralwidget)
        self.button76.setGeometry(QtCore.QRect(290, 330, 51, 51))
        self.button76.setText("")
        self.button76.setObjectName("button76")
        self.button71 = QtWidgets.QPushButton(self.centralwidget)
        self.button71.setGeometry(QtCore.QRect(40, 330, 51, 51))
        self.button71.setText("")
        self.button71.setObjectName("button71")
        self.button75 = QtWidgets.QPushButton(self.centralwidget)
        self.button75.setGeometry(QtCore.QRect(240, 330, 51, 51))
        self.button75.setText("")
        self.button75.setObjectName("button75")
        self.button74 = QtWidgets.QPushButton(self.centralwidget)
        self.button74.setGeometry(QtCore.QRect(190, 330, 51, 51))
        self.button74.setText("")
        self.button74.setObjectName("button74")
        self.button77 = QtWidgets.QPushButton(self.centralwidget)
        self.button77.setGeometry(QtCore.QRect(340, 330, 51, 51))
        self.button77.setText("")
        self.button77.setObjectName("button77")
        self.button82 = QtWidgets.QPushButton(self.centralwidget)
        self.button82.setGeometry(QtCore.QRect(90, 380, 51, 51))
        self.button82.setText("")
        self.button82.setObjectName("button82")
        self.button88 = QtWidgets.QPushButton(self.centralwidget)
        self.button88.setGeometry(QtCore.QRect(390, 380, 51, 51))
        self.button88.setText("")
        self.button88.setObjectName("button88")
        self.button83 = QtWidgets.QPushButton(self.centralwidget)
        self.button83.setGeometry(QtCore.QRect(140, 380, 51, 51))
        self.button83.setText("")
        self.button83.setObjectName("button83")
        self.button86 = QtWidgets.QPushButton(self.centralwidget)
        self.button86.setGeometry(QtCore.QRect(290, 380, 51, 51))
        self.button86.setText("")
        self.button86.setObjectName("button86")
        self.button81 = QtWidgets.QPushButton(self.centralwidget)
        self.button81.setGeometry(QtCore.QRect(40, 380, 51, 51))
        self.button81.setText("")
        self.button81.setObjectName("button81")
        self.button85 = QtWidgets.QPushButton(self.centralwidget)
        self.button85.setGeometry(QtCore.QRect(240, 380, 51, 51))
        self.button85.setText("")
        self.button85.setObjectName("button85")
        self.button84 = QtWidgets.QPushButton(self.centralwidget)
        self.button84.setGeometry(QtCore.QRect(190, 380, 51, 51))
        self.button84.setText("")
        self.button84.setObjectName("button84")
        self.button87 = QtWidgets.QPushButton(self.centralwidget)
        self.button87.setGeometry(QtCore.QRect(340, 380, 51, 51))
        self.button87.setText("")
        self.button87.setObjectName("button87")

        self.button11.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button13.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button15.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button17.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button22.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button24.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button26.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button28.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button31.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button33.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button35.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button37.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button42.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button44.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button46.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button48.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button51.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button53.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button55.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button57.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button62.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button64.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button66.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button68.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button71.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button73.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button75.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button77.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        self.button82.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button84.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button86.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")
        self.button88.setStyleSheet("background-color:#b2b2b2;color:rgba(0,0,0,50%);")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CHECKERS AI - Almibaren"))
        self.buttonPasar.setText(_translate("MainWindow", "TURNO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

